# ws地址
baseUrl: "ws://127.0.0.1:3001"
# 是否连接多个Napcat.OneBot，开启后需在"plugins/napcat-adapter/config/config/botlist.yaml"中填写连接信息
multiple: false
# Token ↓
# accessToken: "your token"
# 是否需要在触发 socket.error 时抛出错误, 默认关闭
throwPromise: false
# ↓ 自动重连(可选)
reconnection:
  enable: true
  attempts: 10
  delay: 5000
# 输出日志时是否连带Bot信息
logbotinfo: true
# 已废弃，不建议开启
isBotuinArray: false
# 大文件阈值，超过设置的阈值则按大文件处理，单位：字节。默认10MB
# 注意，ws单帧限制16MB，超过16MB的文件传输可能会导致WS连接异常
bigFileSize: 10485760
